spring.application.name=codearena-backend
server.port=8080

# A separate Milestone 2 database is used so your previous database is not deleted.
spring.datasource.url=jdbc:mysql://localhost:3306/codearena_milestone2_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Local development JWT secret. Change before deployment.
app.jwt.secret=Q29kZUFyZW5hTWlsZXN0b25lMlNlY3JldEtleUZvckpXVFRva2Vuc0RvTm90VXNlSW5Qcm9kdWN0aW9u
app.jwt.expiration-ms=86400000

app.google.client-id=227558840431-ve48v29ai40vks9tv6e5c5sjrauhf3am.apps.googleusercontent.com
app.cors.allowed-origin=http://localhost:5173

# Local development admin. Change these values before sharing or deploying.
app.bootstrap-admin.enabled=true
app.bootstrap-admin.username=codearena_admin
app.bootstrap-admin.email=admin@codearena.local
app.bootstrap-admin.password=Admin@123

# Gmail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000