CREATE TABLE IF NOT EXISTS problems (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    descriptionMd TEXT NOT NULL,
    difficulty VARCHAR(50) NOT NULL,
    tags VARCHAR(255)
);